const en = {
  welcome: 'Welcome to the Aggrobuddy Application',
  farmer: 'Farmer',
  worker: 'Worker',
  merchant: 'Merchant',
  welcomeFarmer: 'Welcome Farmer',
  login: 'Login',
  userId: 'Enter User Id',
  loginButton: 'Login With OTP',
  newAccount: 'Create New Account',
  FourDigitOTP: 'Please Enter 4 Digit OTP',
  success: 'Success',
  successDescriptions: 'OTP sent Successfully',
  signIn: 'Sign in',
  sec: 'Sec',
  submit: 'Submit',
  name:'Name',
  Select_Gender:'Select Gender',
  Mobile_No:'Mobile No',
  Email_Id:'Email Id',
  Address:'Address',
  Pin_Code:'Pin-Code',
  State:'State',
  City:'City',
  Landmark:'Landmark',
  Create_Account:'Create Account',
  Male:'Male',
  Female:'Female',
  Other:'Other',
  Upload_Profile_Picture:'Upload Profile Picture',
  Open_Gallery:'Open Gallery',
  Open_Camera:'Open Camera',
  Cancel:'Cancel',
  Home:'Home',
  My_Post:'My Post',
  Learn:'Learn',
  Profile:'Profile'
};

const hi = {
  welcome: 'Aggrobuddy आवेदन में आपका स्वागत है',
  farmer: 'किसान',
  worker: 'कर्मचारी',
  merchant: 'बड़ा व्‍यापारी',
  welcomeFarmer: 'किसान आपका स्वागत है !',
  login: 'सत्यापन',
  userId: 'अपना आईडी दर्ज करें',
  loginButton: 'ओटीपी के साथ आगे बढ़े',
  newAccount: 'नया अकाउंट बनाये',
  FourDigitOTP: 'कृपया 4 अंकों का ओटीपी दर्ज करें',
  success: 'सफलता',
  successDescriptions: 'OTP सफलतापूर्वक भेजा गया',
  signIn: 'साइन इन करें',
  sec: 'सेकंड ',
  submit: 'जमा करें',
  name:'नाम',
  Select_Gender:'लिंग चुनें',
  Mobile_No:'मोबाइल नंबर',
  Email_Id:'ईमेल आईडी',
  Address:'पता',
  Pin_Code:'पिन कोड',
  State:'राज्य',
  City:'शहर',
  Landmark:'सीमाचिह्न',
  Create_Account:'खाता बनाएं',
  Male:'पुरुष',
  Female:'महिला',
  Other:'अन्य',
  Upload_Profile_Picture:'प्रोफ़ाइल चित्र अपलोड करें',
  Open_Gallery:'गैलरी खोलें',
  Open_Camera:'कैमरा खोलो',
  Cancel:'रद्द करना',
  Home:'घर',
  My_Post:'मेरा उत्पाद',
  Learn:'सीखना',
  Profile:'प्रोफ़ाइल'
};

export default {en, hi};
