const en = {
  welcome: 'Welcome to the Aggrobuddy Application',
  farmer: 'Farmer',
  worker: 'Worker',
  merchant: 'Merchant',
  welcomeFarmer: 'Welcome Farmer',
  login: 'Login',
  userId: 'Enter User Id',
  loginButton: 'Login With OTP',
  newAccount: 'Create New Account',
  FourDigitOTP: 'Please Enter 4 Digit OTP',
  success: 'Success',
  successDescriptions: 'OTP sent Successfully',
  signIn: 'Sign in',
  sec: 'Sec',
  submit: 'Submit',
  name: 'Name',
  Select_Gender: 'Select Gender',
  Mobile_No: 'Mobile No',
  Email_Id: 'Email Id',
  Address: 'Address',
  Pin_Code: 'Pin-Code',
  State: 'State',
  City: 'City',
  Landmark: 'Landmark',
  Create_Account: 'Create Account',
  Male: 'Male',
  Female: 'Female',
  Other: 'Other',
  Upload_Profile_Picture: 'Upload Profile Picture',
  Open_Gallery: 'Open Gallery',
  Open_Camera: 'Open Camera',
  Cancel: 'Cancel',
  Home: 'Home',
  My_Post: 'My Post',
  Learn: 'Learn',
  Profile: 'Profile',
  title: 'Terms and Conditions',
  description:
    'These Terms and Conditions govern your use of the Farming Application.',
  dataSharing:
    'We may share your data with trusted partners to serve you better.',
  securityMeasures:
    'We implement robust security measures to protect your data.',
  compliance:
    'We comply with all applicable agricultural standards and regulations.',
  updates: 'We reserve the right to update these terms at any time.',
  contactUs: 'For inquiries, contact us at support@example.com.',
  headerText: 'Chance to Earn Extra!',
  subHeaderText: 'Invite your Farmer Friends to Aggrobuddy',
  subHeaderText2:
    'Share your invite link & earn 10% of the profile your farmer friend makes - FOREVER!',
  referralLinkText: 'Your Referral Link',
  copyLinkText: 'Copy the link and share with your farmer friends!',
  tapToCopyText: 'Tap to Copy',
  inviteByText: 'Invite by Social Media',
  facebookText: 'Facebook',
  telegramText: 'Telegram',
  whatsappText: 'Whatsapp',
  orderAndBooking: 'Order and Booking',
  orders: 'Orders',
  soilTestBooking: 'Soil Test Booking',
  weatherAndExpertSuggestion: 'Weather and Expert Suggestion',
  weatherAlert: 'Weather Alert',
  connectWithExpert: 'Connect With Expert',
  earnAndSupport: 'Earn and Support',
  referAndEarn: 'Refer and Earn',
  chatOnWhatsapp: 'Chat on Whatsapp',
  latestMandiNewsAndRateList: 'Latest Mandi News and Rate List',
  latestNews: 'Latest News',
  rateList: 'Rate List',
  accounts: 'Accounts',
  changeLanguage: 'Change Language',
  changeMode: 'Change Mode',
  savedAddress: 'Saved Address',
  termsAndConditions: 'Terms and Conditions',
  privacyPolicy: 'Privacy Policy',
  accountDeletionRequest: 'Account Deletion Request',
  logout: 'Logout',
};

const hi = {
  welcome: 'Aggrobuddy आवेदन में आपका स्वागत है',
  farmer: 'किसान',
  worker: 'कर्मचारी',
  merchant: 'बड़ा व्‍यापारी',
  welcomeFarmer: 'किसान आपका स्वागत है !',
  login: 'सत्यापन',
  userId: 'अपना आईडी दर्ज करें',
  loginButton: 'ओटीपी के साथ आगे बढ़े',
  newAccount: 'नया अकाउंट बनाये',
  FourDigitOTP: 'कृपया 4 अंकों का ओटीपी दर्ज करें',
  success: 'सफलता',
  successDescriptions: 'OTP सफलतापूर्वक भेजा गया',
  signIn: 'साइन इन करें',
  sec: 'सेकंड ',
  submit: 'जमा करें',
  name: 'नाम',
  Select_Gender: 'लिंग चुनें',
  Mobile_No: 'मोबाइल नंबर',
  Email_Id: 'ईमेल आईडी',
  Address: 'पता',
  Pin_Code: 'पिन कोड',
  State: 'राज्य',
  City: 'शहर',
  Landmark: 'सीमाचिह्न',
  Create_Account: 'खाता बनाएं',
  Male: 'पुरुष',
  Female: 'महिला',
  Other: 'अन्य',
  Upload_Profile_Picture: 'प्रोफ़ाइल चित्र अपलोड करें',
  Open_Gallery: 'गैलरी खोलें',
  Open_Camera: 'कैमरा खोलो',
  Cancel: 'रद्द करना',
  Home: 'घर',
  My_Post: 'मेरा उत्पाद',
  Learn: 'सीखना',
  Profile: 'प्रोफ़ाइल',
  title: 'शर्तें और स्थितियाँ',
  description:
    'यहां फार्मिंग ऐप्लिकेशन का उपयोग करने की शर्तें और स्थितियाँ निर्धारित हैं。',
  dataSharing:
    'हम आपके डेटा को विश्वसनीय सहयोगियों के साथ साझा कर सकते हैं ताकि आपकी सेवा में सुधार किया जा सके।',
  securityMeasures:
    'हम आपके डेटा की सुरक्षा के लिए मजबूत सुरक्षा उपाय करते हैं।',
  compliance: 'हम सभी लागू कृषि मानकों और नियमों का पालन करते हैं।',
  updates: 'हम इन शर्तों को किसी भी समय अपडेट करने का अधिकार रखते हैं।',
  contactUs: 'संपर्क के लिए, हमें support@example.com पर ईमेल करें।',
  headerText: 'अतिरिक्त कमाने का अवसर!',
  subHeaderText: 'अपने किसान दोस्तों को अग्रोबड्डी में आमंत्रित करें',
  subHeaderText2:
    'आपके किसान दोस्त के प्रोफ़ाइल से बनाए गए 10% की कमाई का शेयर करें, यह हमेशा रहेगा!',
  referralLinkText: 'आपका रेफरल लिंक',
  copyLinkText: 'लिंक कॉपी करें और अपने किसान दोस्तों से साझा करें!',
  tapToCopyText: 'टैप करें और कॉपी करें',
  inviteByText: 'सोशल मीडिया के माध्यम से आमंत्रित करें',
  facebookText: 'फेसबुक',
  telegramText: 'टेलीग्राम',
  whatsappText: 'व्हाट्सएप',
  orderAndBooking: 'ऑर्डर और बुकिंग',
  orders: 'ऑर्डर',
  soilTestBooking: 'मृदा परीक्षण बुकिंग',
  weatherAndExpertSuggestion: 'मौसम और विशेषज्ञ सुझाव',
  weatherAlert: 'मौसम चेतावनी',
  connectWithExpert: 'विशेषज्ञ से जुड़ें',
  earnAndSupport: 'कमाएँ और समर्थन करें',
  referAndEarn: 'संदर्भ और कमाएं',
  chatOnWhatsapp: 'व्हाट्सएप्प पर चर्चा करें',
  latestMandiNewsAndRateList: 'नवीनतम मंडी समाचार और दर्जी सूची',
  latestNews: 'नवीनतम समाचार',
  rateList: 'दर सूची',
  accounts: 'खाते',
  changeLanguage: 'भाषा बदलें',
  changeMode: 'मोड़ बदलें',
  savedAddress: 'सेवित पता',
  termsAndConditions: 'शर्तें और शर्तें',
  privacyPolicy: 'गोपनीयता नीति',
  accountDeletionRequest: 'खाते की मांग की मांग',
  logout: 'लॉगआउट',
};

export default {en, hi};
